# Generated by Django 4.2.1 on 2025-01-31 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='nombre_madre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre_padre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
